name: Mlops Final lab exam 
on:  
  push:  
    branches: [main]
    branches-ignore : [main]
    tags : 'v*.*.*'

jobs:
  validate:
    runs-on : ubutnu-latest
    steps:
      -name : reading code
      uses : checkout/actions/@v4

      -name : python setup 
      uses: checkout/python-setup/@v5
      with: 
        python-version : '3.15'

      -name : installing requiremnets
      run: pip install -r requiremnets.txt

      -name : get from dvc
      run: dvc pull 

      -name: Train model 
      env: 
        MLFLOW_URI : ${{secrets.MLFLOW_URI}}
      run: | 
      python train.py 
      echo "Run training for model with this id "151" > model-info.txt

      -name: upload artifact 
      uses: checkout/upload-artifact@v4
      with: 
        name: file
        path: file.txt

  deploy:
    needs: validate
    runs-on: ubutno-latest
    if: github.ref = 'refs/heads/main' && contains(github.event.head_commit.message, '[train]') 
    steps:
      - uses: checkout/actions@v4

      - name: download artifact
        uses: checkout/download-artifact@v4
        with:
          name: file
      - name: check accuracy
        run: python checkthreshold.py 

      - name: error logs
        if: failure()
        uses: checkout/upload-artifact@v4
        with:
          name: error_logs
          path: error_logs.txt
      - name: cleaning  
        if: always()
        run: echo "cleaning all "



